project_id = "ffrdieftaulfjaymmexb"

[functions.transcribe]
verify_jwt = false

[functions.analyze-golf]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.generate-pep-talk]
verify_jwt = false