// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffrdieftaulfjaymmexb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmcmRpZWZ0YXVsZmpheW1tZXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3ODA5NzksImV4cCI6MjA0OTM1Njk3OX0.C-vtcsDCmGQQRFQiNqngVDf-GAd00dt1lxGd2Y_RVXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);